config/routes.rb
Rails.application.routes.draw do

  root 'webinars#index'

  get '/auth' => 'sessions#index'
  get '/auth/:provider/callback' => 'sessions#create'
  post'/auth/:provider/callback' => "sessions#create" if Rails.env.development? #for the 'developer' strategy
  delete '/auth/signout' => 'sessions#destroy'

  resources :webinars, except: [:destroy] do
    resources :votes, only: [:create, :destroy]
    resources :stars, only: [:create, :destroy]
  end

  resources :users, only: [:show]

  resources :suggestions, except: [:edit, :update] do
    resources :suggestion_votes, only: [:create]
  end

end

app/models/star.rb
class Star < ActiveRecord::Base

  belongs_to :webinar, counter_cache: true
  belongs_to :user

  validates :webinar_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :webinar_id }

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base

  belongs_to :user
  has_many :suggestion_votes

  validates :description, :user_id, presence: true

  scope :latest, -> { order(created_at: :desc) }

end

app/models/suggestion_vote.rb
class SuggestionVote < ActiveRecord::Base

  belongs_to :suggestion, counter_cache: true
  belongs_to :user

  validates :suggestion_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :suggestion_id }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :webinars
  has_many :votes
  has_many :stars
  has_many :suggestions
  has_many :suggestion_votes

  def star_id_for(webinar_id)
    stars.find{ |s| s.webinar_id == webinar_id }.try(:id)
  end

  def vote_id_for(webinar_id)
    votes.find{ |v| v.webinar_id == webinar_id }.try(:id)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :webinar, counter_cache: true
  belongs_to :user

  validates :webinar_id, :user_id, presence: true
  validates :user_id, uniqueness: { scope: :webinar_id }

end

app/models/webinar.rb
class Webinar < ActiveRecord::Base

  belongs_to :user
  has_many :votes
  has_many :stars

  validates :user_id, :title, :description, :planned_date, presence: true
  validates :youtube_url, :language, presence: true, if: :webinar_aired?
  validate :language_option_is_valid, if: :webinar_aired?
  validate :youtube_url_is_valid, if: :webinar_aired?

  scope :latest, -> { order(created_at: :desc) }
  scope :upcoming, -> { where(upcoming: true).where('planned_date > ?', Time.current).order(planned_date: :asc) }
  scope :aired, -> { where(upcoming: [false, nil]) }

  def webinar_aired?
    !self.upcoming
  end

  def upcoming?
    self.upcoming
  end

  def mark_as_reminded!
    self.update_attribute(:reminded, true)
  end

  private

  def language_option_is_valid
    unless ['PL', 'EN'].include? self.language.to_s.upcase
      self.errors.add(:language, 'must be PL or EN')
    end
  end

  def youtube_url_is_valid
    return false unless self.youtube_url.present?
    match_result = self.youtube_url =~ /www.youtube.com\/watch/
    unless match_result.to_i > 0
      self.errors.add(:youtube_url, 'please paste a full youtube url')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception

  helper_method :current_user, :authenticated?, :sign_in, :sign_out

  before_filter :authentication_check

  expose(:current_user) { get_current_user }

  private

  def get_current_user
    User.find(session[:user_id]) if session[:user_id].present?
  end

  def authenticated?
    current_user.present?
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
  end

  def authentication_check
    redirect_to auth_path unless authenticated?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authentication_check
  skip_before_filter :verify_authenticity_token, only: [:create] #for 'developer' strategy

  respond_to :json, only: [:destroy]

  expose(:failure_message) { params[:message].presence || 'unknown' }
  expose(:github_auth_path) { '/auth/github' }

  def index
  end

  def create
    user = Authentication::UserBuilder.new(auth_hash).find_or_build
    if user.persisted? || user.save
      sign_in user
      redirect_to root_path
    else
      render text: "Couldn't log you in!"
    end
  end

  def destroy
    sign_out
    redirect_to auth_url
  end

  def failure
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  expose(:webinar) { Webinar.find(webinar_params[:webinar_id]) }
  expose(:star)

  def create
    star.user_id = current_user.id
    star.webinar_id = webinar.id
    if star.save
      redirect_to webinars_path
    else
      redirect_to webinars_path, error: I18n.t('controllers.star.create.error')
    end
  end

  def destroy
    star.destroy
    if star.destroyed?
      redirect_to webinars_path
    else
      redirect_to webinars_path, error: I18n.t('controllers.star.destroy.error')
    end
  end

  private

  def webinar_params
    params.permit(:webinar_id)
  end

end

app/controllers/suggestion_votes_controller.rb
class SuggestionVotesController < ApplicationController
  expose(:suggestion) { Suggestion.find(suggestion_params[:suggestion_id]) }
  expose(:suggestion_vote)

  def create
    suggestion_vote.user_id = current_user.id
    suggestion_vote.suggestion_id = suggestion.id
    if suggestion_vote.save
      redirect_to suggestions_path
    else
      redirect_to suggestions_path, error: I18n.t('controllers.suggestion_votes.create.error')
    end
  end

  private

  def suggestion_params
    params.permit(:suggestion_id)
  end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  expose_decorated(:suggestions) { Suggestion.latest.page(params[:page]).per(25) }
  expose(:suggestion, attributes: :suggestion_params)

  def index
  end

  def new
  end

  def create
    suggestion.user_id = current_user.id
    if suggestion.save
      redirect_to suggestions_path
    else
      render :new
    end
  end

  def destroy
  end


  private

  def suggestion_params
    params.require(:suggestion).permit(:description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose_decorated(:user)

  def show
    if user.id != current_user.id
      redirect_to webinars_path, alert: 'nuh uh'
    end
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  expose(:webinar) { Webinar.find(webinar_params[:webinar_id]) }
  expose(:vote)

  def create
    vote.user_id = current_user.id
    vote.webinar_id = webinar.id
    if vote.save
      redirect_to webinars_path
    else
      redirect_to webinars_path, error: I18n.t('controllers.votes.create.error')
    end
  end

  def destroy
    vote.destroy
    if vote.destroyed?
      redirect_to webinars_path
    else
      redirect_to webinars_path, error: I18n.t('controllers.votes.destroy.error')
    end
  end

  private

  def webinar_params
    params.permit(:webinar_id)
  end

end

app/controllers/webinars_controller.rb
class WebinarsController < ApplicationController
  expose_decorated(:webinars) { Webinar.aired.latest.includes(:user).page(params[:page]) }
  expose_decorated(:upcoming_webinar, decorator: WebinarDecorator) { Webinar.upcoming.first }
  expose(:webinar, attributes: :webinar_params)

  def index
  end

  def new
  end

  def create
    webinar.user_id = current_user.id
    if webinar.save
      redirect_to webinars_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if webinar.save
      redirect_to webinars_path
    else
      render :edit
    end
  end

  private

  def webinar_params
    params.require(:webinar).permit(
      :title,
      :youtube_url,
      :description,
      :language,
      :translation_available,
      :blogpost_url,
      :doc_url,
      :code_url,
      :upcoming,
      :planned_date
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    options = { hard_wrap: true,
                filter_html: true,
                autolink: true,
                no_intraemphasis: true,
                fenced_code: true,
                gh_blockcode: true
    }
    mdwn = ::Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    mdwn.render(text).html_safe
  end

  def flash_msg_class(name)
    css_classes_for_flash.fetch(name.to_sym, 'info')
  end

  def faded_class(var)
    'faded' unless var
  end

  private

  def css_classes_for_flash
    {
      notice: 'success',
      error: 'danger',
      alert: 'warning',
      info: 'info'
    }
  end

end

app/views/layouts/_flash_messages.html.haml
.row
  .col-md-12
    .flash-messages
      - flash.each do |name, msg|
        .alert{ class: "alert alert-#{flash_msg_class(name)}", role: "alert" }
          = content_tag :div, msg
          - if @errors && @errors[name.to_sym]
            %ul
              - @errors[name.to_sym].each do |error_message|
                %li= error_message

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-webinarium{ role: "navigation" }
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{ type: "button", data: { target: "#header-navbar-collapse", toggle: "collapse" } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{ href: root_path } Webinarium
    #header-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if authenticated?
          %li
            = link_to t('common.add'), new_webinar_path
          %li
            = link_to t('common.suggestions'), suggestions_path
      %ul.nav.navbar-nav.navbar-right
        - if authenticated?
          %li
            %img.user-img{ src: current_user.image_url }
          %li.dropdown
            %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#" }
              = current_user.name
              %span.caret
            %ul.dropdown-menu{ role: "menu" }
              %li
                = link_to t('common.my_profile'), user_path(current_user)
              %li
                = link_to t('common.logout'), auth_signout_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Webinarium
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    /[if lt IE 9]
      %script{ src: "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js" }
      %script{ src: "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" }
  %body
    = render 'layouts/navbar'
    .container
      .row
        = render 'layouts/flash_messages'
        = yield

app/views/suggestions/_form.html.haml
= simple_form_for suggestion do |f|
  = f.input :description, as: :text, input_html: { rows: 20, cols: 150 }
  = f.submit t('common.save'), class: 'btn btn-info'

app/views/suggestions/_suggestion.html.haml
.row
  .col-md-10
    = markdown suggestion.description
  .col-md-2
    .row
      .count.liked-by
        .box.icon-box
          .glyphicon.glyphicon-thumbs-up
        .box.count-box
          = suggestion.suggestion_votes_count
    .row
      = suggestion.upvote_link(current_user)
.row
  .col-md-12
    %hr

app/views/suggestions/index.html.haml
.row
  .col-md-12
    = link_to t('.add'), new_suggestion_path, class: 'btn btn-default'
.row
  .col-md-12
    %h3= t('.title')

= render partial: 'suggestion', collection: suggestions

= paginate suggestions

app/views/suggestions/new.html.haml
.row
  .col-md-12
    %h3= t('.title')
.row
  .col-md-12
    = render 'form', suggestion: suggestion

app/views/users/_liked_webinar.html.haml
.col-md-12.col-xs-12
  .row
    .col-md-10.col-xs-8
      %span.author= "#{webinar.user.name}:"
      = webinar.title
    .col-md-2.col-xs-4
      .pull-right
        = webinar.like_link(current_user)

app/views/users/_my_webinar.html.haml
.col-md-12.col-xs-12
  .row
    .col-md-10.col-xs-8
      = webinar.title
    .col-md-2.col-xs-4
      .pull-right
        = link_to t('common.edit'), edit_webinar_path(webinar), class: 'btn btn-info pull-right'

app/views/users/_starred_webinar.html.haml
.col-md-12
  .row
    .col-md-10.col-xs-8
      %span.author= "#{webinar.user.name}:"
      = webinar.title
    .col-md-2.col-xs-4
      .pull-right
        = webinar.star_link(current_user)

app/views/users/show.html.haml
%div{role: "tabpanel"}
  %ul.nav.nav-tabs{role: "tablist"}
    %li.active{role: "presentation"}
      %a{"aria-controls" => "added", "data-toggle" => "tab", href: "#added", role: "tab"} Added
    %li{role: "presentation"}
      %a{"aria-controls" => "starred", "data-toggle" => "tab", href: "#starred", role: "tab"} Starred
    %li{role: "presentation"}
      %a{"aria-controls" => "liked", "data-toggle" => "tab", href: "#liked", role: "tab"} Liked

  .tab-content

    #added.tab-pane.active{role: "tabpanel"}
      .row
        .col-md-12
          %h3= t('.added_by_me')
        - user.webinars.each do |webinar|
          = render 'my_webinar', webinar: webinar.decorate

    #starred.tab-pane{role: "tabpanel"} 
      .row
        .col-md-12
          %h3= t('.starred_by_me')
        - user.starred_webinars.each do |webinar|
          = render 'starred_webinar', webinar: webinar.decorate


    #liked.tab-pane{role: "tabpanel"} 
      .row
        .col-md-12
          %h3= t('.liked_by_me')
        - user.liked_webinars.each do |webinar|
          = render 'liked_webinar', webinar: webinar.decorate

app/views/webinars/_form.html.haml
= simple_form_for webinar, html: { class: 'form-vertical' } do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.input :upcoming, as: :boolean
  = f.input :planned_date
  = f.input :youtube_url
  = f.input :language, collection: ['PL','EN']
  = f.input :translation_available, as: :boolean
  = f.input :blogpost_url
  = f.input :doc_url
  = f.input :code_url
  = f.submit t('common.save'), class: 'btn btn-info'

app/views/webinars/_upcoming_webinar.html.haml
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        %h3.panel-title= t('.title')
      .panel-body
        .row
          .col-md-8.col-xs-8
            .upcoming-webinar
              %span.title= webinar.title
              %p= webinar.description
          .col-md-4.col-xs-4
            %img.pull-right.author-image{ src: webinar.user.image_url }
      .panel-footer
        Tune in on
        %strong= l webinar.planned_date, format: :short

app/views/webinars/_webinar.html.haml
.row
  .col-md-5.col-xs-12
    %img{ src: webinar.thumbnail }
  .col-md-7.col-xs-12
    .row
      .col-md-2
        .tile.tile-video
          = link_to "#", data: { toggle: 'modal', target: "#youtubeModal", src: "//www.youtube.com/embed/#{webinar.youtube_video_id}" }, class: 'youtubeModalButton'  do
            %span.glyphicon.glyphicon-play
        .tile-description
          = t('.video')
      .col-md-2
        .tile.tile-lang
          %span= webinar.language
        .tile-description
          = t('.language')
      .col-md-2
        = render 'webinar_link_tile', tilename: 'blog', link: webinar.blogpost_url, glyphicon: 'book'
      .col-md-2
        = render 'webinar_link_tile', tilename: 'doc', link: webinar.doc_url, glyphicon: 'file'
      .col-md-2
        = render 'webinar_link_tile', tilename: 'code', link: webinar.code_url, glyphicon: 'list-alt'
      .col-md-2
        .tile.tile-subs{ class: faded_class(webinar.translation_available) }
          %span.glyphicon.glyphicon-subtitles
        .tile-description
          = t('.subtitles')
    .row
      .col-md-12
        %h3
          %span.author= "#{webinar.user.name}:"
          = webinar.title
      .col-md-12
        %p= webinar.description
.row
  .col-md-5
    .count.liked-by
      .box.icon-box
        .glyphicon.glyphicon-thumbs-up
      .box.count-box
        = webinar.vote_count
    .count.starred-by
      .box.icon-box
        .glyphicon.glyphicon-star
      .box.count-box
        = webinar.star_count
  .col-md-7
    = webinar.like_link(current_user.vote_id_for(webinar.id))
    = webinar.star_link(current_user.star_id_for(webinar.id))
    - if webinar.user.id == current_user.id
      = link_to t('common.edit'), edit_webinar_path(webinar), class: 'btn btn-info pull-right'

.row
  .col-md-12
    %hr

app/views/webinars/_webinar_link_tile.html.haml
.tile{ class: "#{faded_class(link.present?)} tile-#{tilename}" }
  - if link.present?
    = link_to link do
      %span.glyphicon{ class: "glyphicon-#{glyphicon}" }
  - else
    %span.glyphicon{ class: "glyphicon-#{glyphicon}" }
.tile-description
  =t(".#{tilename}")

app/views/webinars/edit.html.haml
.row
  .col-md-12
    %h3= t('.title')
.row
  .col-md-12
    = render 'form', webinar: webinar

app/views/webinars/index.html.haml
- if upcoming_webinar.present?
  = render 'upcoming_webinar', webinar: upcoming_webinar


.row
  .col-md-12
    %h3= t('.title')

= render partial: 'webinar', collection: webinars

#youtubeModal.modal.fade{ role: "dialog", tabindex: "-1" }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ data: { dismiss: "modal" }, type: "button" }
          %span{ aria: { hidden: "true" } } &times;
          %span.sr-only Close
      .modal-body
        %iframe(frameborder="0" allowFullScreen width='99.6%' height='360')
      .modal-footer

= paginate webinars

app/views/webinars/new.html.haml
.row
  .col-md-12
    %h3= t('.title')
.row
  .col-md-12
    = render 'form', webinar: webinar